navgurukul/sama

package-lock.json, src/OppsFiles/UserDetails/Userdatabulkupload.js, src/OppsFiles/UserDetails/Userdetails.js
updated UI of user detail and store for bulk data
=> UI update sama

src/OppsFiles/UserDetails/Userdetails.js
Added the loader, file name, and image upload.
=> Rewrite the removed code.

src/Pages/NGORegistration/RegistrationForm.js
Updated backend Functionality.
=> Added the form submission/

src/Pages/NGORegistration/RegistrationForm.js
=> Fixed some feedbacks.

src/OppsFiles/UserDetails/Userdetails.js
=> add dropdow

src/App.js, src/Dashboard/BeneficiaryData/index.js
did some changes based on Laptop tagging.
=> Resolve some issues.

src/App.js, src/Dashboard/BeneficiaryData/index.js, src/OppsFiles/UserDetails/Userdetails.js
=> Development to main

package-lock.json, src/App.js, src/Dashboard/AdminNgo/TabNavigation.js, src/Dashboard/Preliminary/PreDestibution.js, src/Dashboard/Preliminary/PreliminaryForm.js, src/Dashboard/Preliminary/index.js, src/Pages/Login/OpsLogin/Opslogin.js
Worked to add the small and large ngo functionality.
=> Worked to add the small and large ngo functionality.

src/Dashboard/AdminNgo/TabNavigation.js, src/Dashboard/AdminNgo/index.js, src/Dashboard/BeneficiaryData/index.js, src/Dashboard/Preliminary/PreliminaryForm.js, src/Dashboard/Preliminary/index.js, src/Pages/Login/OpsLogin/Opslogin.js
I fixed some requested feedback.
=> Fixed some requested feedback.

src/App.js, src/Dashboard/Preliminary/PreDestibution.js, src/Dashboard/Preliminary/index.js, src/Pages/DocumentReupload/DocumentReupload.js, src/Pages/Login/OpsLogin/Opslogin.js, src/components/AttentionNeeded/AttentionNeeded.js, src/components/DocumentUpload/DocumentUpload.js, src/components/SubmissionSuccess/SubmissionSuccess.js
Created the Multiple document Upload feature for the ngo.
=> Reupload docs

public/index.html
Added Insight Tag Using Google Tag Manager
=> LinkedIn Insight Tag Added using Google Tag Manager

src/App.js, src/OppsFiles/UserDetails/Userdatabulkupload.js, src/OppsFiles/UserDetails/Userdetails.js, src/Pages/DocumentReupload/DocumentReupload.js, src/Pages/LaptopData/UploadExcel.js, src/components/AttentionNeeded/AttentionNeeded.js, src/components/DocumentUpload/DocumentUpload.js, src/components/SubmissionSuccess/SubmissionSuccess.js
https://github.com/navgurukul/sama/compare/NGO-design-checks?expand=1
=> Ngo design checks

src/components/Header/Navbar.js
=> changes in OPS

src/Dashboard/Preliminary/MonthlyNgoReport.js
=> Priliminary buttons

src/Dashboard/BeneficiaryData/NGOTable.js, src/Dashboard/Preliminary/YearlyNgoReport.js
=> fixed ngo table and yearlyngo

src/Pages/NGORegistration/RegistrationForm.js
=> Ngo registration bug fixes

src/Dashboard/Preliminary/PreliminaryForm.js, src/OppsFiles/UserDetails/Userdetails.js
=> Form validation fixes

src/Dashboard/BeneficiaryData/AdminTable.js, src/Dashboard/MontlyReport/index.js, src/Dashboard/YearlyReport/index.js
fixed admin table and add margin botton in monthly matrics
=> fixed admin table and add margin botton in monthly matrics

src/App.js, src/Pages/Login/OpsLogin/Opslogin.js, src/Privaterouts.js
Fixing the Routing for the ngos.
=> Fixed Private routing for multiple ngo's type.

src/Pages/NGORegistration/RegistrationForm.js
condition for already registerd contact number
=> condition for already registerd contact number

src/Dashboard/AdminNgo/DataUpload.js, src/Dashboard/AdminNgo/index.js, src/Dashboard/BeneficiaryData/AdminTable.js, src/Dashboard/BeneficiaryData/NGOTable.js, src/Dashboard/ManageStatuses/DeleteStatusDialog/index.js, src/Dashboard/ManageStatuses/index.js, src/components/DocumentUpload/DocumentUpload.js, src/components/Header/Navbar.js
=> fixed styling

src/Dashboard/BeneficiaryData/AdminTable.js, src/Dashboard/BeneficiaryData/EditUser/EditUserPage.js, src/Dashboard/Preliminary/PreliminaryForm.js, src/OppsFiles/UserDetails/Userdetails.js, src/Pages/LaptopData/LaptopData.js, src/Pages/LaptopData/LaptopForm.js, src/Pages/LaptopData/UploadExcel.js, src/Pages/LaptopTagging/EditButton.js, src/Pages/LaptopTagging/index.js, src/Pages/Login/OpsLogin/Opslogin.js
=> Updated the api's

src/Dashboard/BeneficiaryData/AdminTable.js, src/Dashboard/BeneficiaryData/BeneficiaryProfile.js, src/Dashboard/BeneficiaryData/HistoryStatusPopup.js, src/Dashboard/BeneficiaryData/NGOTable.js, src/Dashboard/BeneficiaryData/index.js, src/Dashboard/ManageStatuses/index.js, src/Dashboard/MontlyReport/index.js, src/Dashboard/Preliminary/PreDestibution.js, src/Dashboard/Preliminary/index.js, src/Dashboard/YearlyReport/index.js, src/Dashboard/index.js, src/OppsFiles/UserDetails/Userdatabulkupload.js, src/Pages/LaptopData/LaptopData.js, src/Pages/Login/OpsLogin/Opslogin.js, src/components/NgoDashboard/ngodashboard.js
Updated all the APIs with the new APIs.
=> Updated all the API's

src/CorporateDB/LocationImpact/LocationWiseImpact.css, src/CorporateDB/LocationImpact/index.js
=> Location map figma

src/Pages/NGORegistration/RegistrationForm.js
add validation for registration number
=> add validation for registration number

src/Dashboard/MontlyReport/index.js, src/Dashboard/Preliminary/MonthlyNgoReport.js, src/Dashboard/Preliminary/MothlyReportingForm.js, src/Dashboard/Preliminary/PreDestibution.js, src/Dashboard/Preliminary/index.js, src/components/Header/Navbar.js
Updated the Format of the monthly Data.
=> Updated the Database data format for the monthly update.

src/CorporateDB/LocationImpact/LocationWiseImpact.css, src/CorporateDB/LocationImpact/index.js
=> added changes in map

src/Dashboard/AdminNgo/index.js
Added the Doner column in the NGO lists.
=> Added the Doner.

src/Pages/About/CorporatePartner/CorporateForm.js, src/Pages/About/OurTeam/OurTeam.js, src/Pages/About/OurTeam/style.js, src/Pages/About/Service/ServiceCards.js, src/Pages/OurApproach/OurApproach.js, src/common/StayConnected.js
=> Pages modified

src/Pages/About/About.js, src/Pages/About/CommunityPartners/CommunityPartners.js, src/Pages/About/CorporatePartner/CorporatePartner.js, src/Pages/About/OurGoverment/OurGoverment.js, src/Pages/About/OurTeam/OurTeam.js, src/Pages/Home/index.js, src/common/StayConnected.js, src/components/Footer/Footer.js, src/components/Header/Navbar.js
=> header and footer

src/Pages/About/About.js, src/Pages/About/CommunityPartners/CommunityForm.js, src/Pages/About/CommunityPartners/CommunityPartners.js, src/Pages/About/CommunityPartners/GreenBox.js, src/Pages/About/OurTeam/style.js, src/Pages/About/Service/StatsSection.js, src/Pages/About/Service/index.js
=> Community page

src/App.js, src/CorporateDB/MonthlyImpact/DetailView.js, src/CorporateDB/MonthlyImpact/index.js, src/Dashboard/AdminNgo/NgoProfile.js, src/components/Header/Navbar.js
Added the Monthly impact feature.
=> Added the monthly Impect feature.

package-lock.json, src/CorporateDB/CompactDateRangePicker.js, src/CorporateDB/LocationImpact/LocationWiseImpact.css, src/CorporateDB/LocationImpact/index.js, src/CorporateDB/MonthlyImpact/DetailView.js, src/CorporateDB/MonthlyImpact/index.js, src/CorporateDB/MonthlyImpact/styles/MonthlyImpact.css, src/CorporateDB/YearlyImpact/DynamicLineChart.js, src/CorporateDB/YearlyImpact/NGOTrainedTable.js, src/CorporateDB/YearlyImpact/index.js, src/CorporateDB/YearlyImpact/styles/YearlyImpect.css, src/CorporateDB/index.js
=> Styling fixed corporate db

src/CorporateDB/MonthlyImpact/index.js
Updated the feature and showed default data for monthly impact even if date range is not selected.
=> Updated the feature and showing default data for monthly impact.

src/CorporateDB/LocationImpact/LocationWiseImpact.css, src/CorporateDB/LocationImpact/index.js, src/CorporateDB/MonthlyImpact/DetailView.js, src/CorporateDB/MonthlyImpact/index.js, src/CorporateDB/YearlyImpact/index.js, src/CorporateDB/index.js, src/Pages/OurApproach/OurApproach.js
=> Revert "Corporate changes"

src/CorporateDB/MonthlyImpact/DetailView.js, src/CorporateDB/MonthlyImpact/index.js, src/CorporateDB/index.js
Added some style changes in corporate DB.
=> added some styling fixes.

src/Pages/About/OurTeam/OurTeam.js
Fixed some out team page feedback.
=> Fixing the team page.

src/Pages/About/CommunityPartners/CommunityForm.js, src/Pages/About/CommunityPartners/ImageBox.js, src/Pages/About/CorporatePartner/CorporateForm.js, src/Pages/About/OurGoverment/OurGovermentForm.js, src/Pages/About/OurTeam/style.js, src/Pages/About/Service/HeaderText.js, src/Pages/About/Service/StatsSection.js, src/Pages/Donate/Donate.js, src/Pages/Home/TestimonialSlider.js
=> changes done

src/Pages/About/CorporatePartner/CorporateForm.js, src/Pages/About/OurGoverment/OurGoverment.js, src/Pages/About/OurTeam/OurTeam.js, src/Pages/About/Service/HeaderText.js, src/Pages/Donate/Donate.js, src/Pages/Home/ContactForm.js, src/Pages/Home/index.js, src/Pages/OurApproach/OurApproach.js, src/components/Footer/Footer.js, src/components/Header/Navbar.js
=> changes in gap

src/Pages/About/OurTeam/OurTeam.js, src/components/Footer/Footer.js
=> vedio update

package-lock.json, public/index.html
=> Updating the display name.

public/index.html
=> Updating the display name

src/Pages/About/OurTeam/OurTeam.js, src/Pages/About/OurTeam/style.js
=> Fixed the our team gif issue.

src/OppsFiles/UserDetails/Userdetails.js, src/Pages/LaptopData/LaptopForm.js, src/Pages/LaptopData/common.css
=> Form valid

src/Dashboard/AdminNgo/NGOLaptopTable.js, src/Pages/About/OurGoverment/OurGovermentForm.js, src/Pages/LaptopData/LaptopForm.js, src/Pages/LaptopTagging/EditButton.js, src/components/OPS/LaptopTable/FilterPanel.js
=> Ops feedback changes

src/Pages/LaptopData/LaptopForm.js
=> Ops form valid

src/App.js, src/Pages/LaptopTagging/LaptopDetails.js, src/components/Header/Navbar.css, src/components/Header/Navbar.js, src/components/OPS/LaptopAudit.js, src/components/OPS/LaptopTable/FilterPanel.js
=> added header in ops

src/Pages/LaptopTagging/index.js, src/components/OPS/LaptopTable/LaptopStatus.js, src/components/OPS/LaptopTable/LaptopTable.js, src/components/OPS/OpsWelcome.js
=> did changes in ops warehouse

src/App.js, src/Pages/LaptopTagging/LaptopDetails.js, src/Pages/LaptopTagging/index.js, src/Pages/Login/OpsLogin/Opslogin.js, src/Pages/Login/OpsLogin/SignupForm.js, src/components/OPS/LaptopTable/FilterPanel.js, src/components/OPS/LaptopTable/LaptopStatus.js, src/components/OPS/LaptopTable/LaptopTable.js
=> remove filters

src/App.js, src/Pages/Login/OpsLogin/Opslogin.js, src/Pages/Login/OpsLogin/SignupForm.js, src/components/Header/Navbar.js, src/components/Header/Registration.js
=> added reistration page

src/components/Header/Navbar.js
changed highlighted tabs color
=> changed highlighted tabs color

src/Pages/LaptopTagging/BulkEditPanel.js, src/Pages/LaptopTagging/index.js, src/common/StayConnected.js
=> Multi selec issue

src/components/OPS/LaptopAudit.js
=> search issue

src/Pages/Home/TestimonialSlider.js, src/components/OPS/LaptopAudit.js
=> Audit issues

src/Dashboard/AdminNgo/NGOLaptopTable.js, src/Pages/LaptopTagging/LaptopDetails.js, src/Pages/LaptopTagging/index.js, src/components/Header/Navbar.js, src/components/OPS/LaptopAudit.js, src/components/OPS/LaptopTable/FilterPanel.js, src/components/OPS/LaptopTable/LaptopTable.js
=> Warehouse sorting

src/Pages/LaptopTagging/LaptopDetails.js, src/Pages/LaptopTagging/index.js, src/components/Header/Navbar.js, src/components/OPS/LaptopAudit.js, src/components/OPS/LaptopTable/FilterPanel.js, src/components/OPS/LaptopTable/LaptopTable.js
added all new filters and date format
=> added all new filters and date format

src/Dashboard/AdminNgo/index.js, src/Pages/LaptopTagging/index.js
change the data value and filter correctly.
=> change the data value corectly

src/Pages/DonerCSR/LaptopTracking.js, src/Pages/DonerCSR/Ngopartner.js
=> table work done

src/App.js, src/Pages/DonerCSR/DonorCSRRoute.js, src/Pages/DonerCSR/LaptopPipeline.js, src/Pages/DonerCSR/LaptopTracking.js, src/Pages/DonerCSR/Ngopartner.js, src/Pages/DonerCSR/Overview.js, src/Pages/DonerCSR/OverviewHeader.js, src/Pages/DonerCSR/SideBar.js
=> donor specipic UI
